#!/bin/bash

# Error handling function for cron
function error_exit
{
        echo "$1" 1>&2
        exit 1
}

scriptpath=$(dirname $0)
s3confpath="$HOME/.aws/s3-config"

if [ -f $s3confpath ];
then
   export AWS_CONFIG_FILE=$s3confpath
else
   error_exit "S3 credentials do not exist"
fi

workspace=workspace
workspace=$scriptpath/$workspace

. $scriptpath/piwikToken || error_exit "can not find piwik API token"

# preparing tracking javascript files
apicall=$(curl -sS -w "\n" "http://localhost/index.php?module=API&method=ContainerTag.buildTags&external=1&format=JSON&token_auth=$piwikToken")
grep success <<< $apicall || error_exit "API call to generate js objects failed with error: $apicall"

#set the filesystem locations for the javascript objects
v1=/usr/share/nginx/piwik/html/plugins/ContainerTag/js/*.js
v2=/usr/share/nginx/piwik/html/plugins/ContainerTag/js/v2/*.js

# This is where we will sync the data to S3 from
rm -Rf $workspace || error_exit "Could not remove workspace directory: $workspace"
mkdir $workspace || error_exit "Could not create directory: $workspace"

# Copy all the files and fiddle the names.
for path in $v1
do
  file="tracking${path##*/}"
  cp $path $workspace/$file || error_exit "copying file $path to $workspace/$file failed"
done 

for path in $v2
do
  file="t${path##*/}"
  cp $path $workspace/$file || error_exit "copying file $path to $workspace/$file failed"
done

aws s3 sync $workspace s3://js-objects || error_exit "S3 Sync Failed"
