#!/bin/bash
cd ~

#Install git
yum install git -y

#salt-bootstrap installs salt-master and salt-minion
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sh install_salt.sh -M git v2015.5.1

# Create Salt minion config
cat << _EOF_ > /etc/salt/minion
master: localhost
id: master
_EOF_

cat << _EOF_ > /etc/salt/grains # this is needed for the salt mine
roles:
  - master
_EOF_

# Add SSH private key so we can clone salt configs from GitHub

mkdir ~/.ssh/ 
cat << _EOF_ > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAvaUmYrr45jnMt6ooXi2Hu08IuHWpJWG1P+Sj2RBQhahLxMwc
ow/o5jREJSLXUpJO2F0y7Ur77j0j/4n6IkR+G2cnNuKycwBBRCdFusnz+evXx5BK
Y5T/RK5ly13IiYcgKjkKAADkYYkR5tLsI6RutZKE+N+iIHix5ojXtj/oPSSFKguD
xDTgK1cU66zE3Vs0DsGMMh1QmxysXN8VeoZvjc5QrjbmxwfGsbhTkW5d2BfNDI4g
FNZ8U3qZQML05L239cIqlcJfTPRjdgrVekZ+wH4WbRAQbLJ7K/e/htsNFD1z11tJ
tpshfAjMfvRejzFCqeYefQV3WSjQDzHo38Mg8wIDAQABAoIBAEyVvxSr8Qv4V4Xs
P3UY6fFoj1r+mRoxhSKSUOC9x+bR+hc1XnMzX5hnjwV4NoBv+UtDB+fwGiExq7Hs
pIjmJA8o7xspHWt3tOOzAGPYXqCU74T17jSc3SF9VDp2Wx++4+xpMHKj6ZbB5erT
Tu1t4A+PZgejODPoyd8RcBt3X3Ag91Un9UMfIgoiym8mQXZuTnocZ6IzhTpZBS9Q
YVmM4WM8jV+ZO4tin5cEtwdVMssUgEneYDxxQZoTJFLKsZIF/w3mdZ9YYbTwoMYq
s8KOr+4zFH6WxdYxmcKBIQRmacpzWD0uU9qcGsCB2/LAtpGEub62owaH5cavDQZW
683QflECgYEA5Q5c7vIT0qMWig9eADr9bT2Ks980a1cY6QCiOwsFOBv66qFcJ5KM
y+J8sVPM37QSxybD2EGoZuSLKt3F8EydYIYptZSKtI+O3XW0aa6YaTktEXdJkObV
w+b1+k378KXBTus1VMmGiodtFQeY4iT2/EZgIoslFLsJcpO2GmflI20CgYEA0/P9
3/LWslMt3lFmWC0iZXJpklNh2YE9tShMjjIAwL0yXDOs2R9BtRdtfKHqhWSBWAQZ
JsZW5wefaf7xSoCRTy0l75SIsgU0QMZw+7bq+rAMacrayZtrKGbGk9tXV4sWCBer
mvXJTYh63Qx8azH1S7bXUMON5Il0FQ70mVGeOd8CgYAH3Shfo7v+fU7myoRFqcDN
oVFDv6QDE2hth3IKaORy+rLwnz2UtjlTPqFdTS05eOs0HyaWJBrt/WaxwA9topO8
np6L91+Tt2IGRGY/QplE84uSj+/co7AvG5zSTR8bMfWjCfw4vvp5gxDBqhMboH1C
SABA71oEji9S2bNk0LBTOQKBgQCdFwB5xCUGBApB9Piyr7kHkVXXor8qEtTmeJjM
5xiRwWga2B3qynTLwDJgpi0IcqY+0sLFb0kncAnh6JdzjXilQyQTvnXV42+H9sv0
c+0SofqBSl0AAZXZWtsg6PeCJc7NbqW8cyCgu1+8h62LUXqphDlvXZDD6nBDz1LQ
c6Ke5wKBgQCnROT9saBU8Tgt0yiRNTEkJs/K2zFATBayOXkqaSOw2tSOsMz5y6hH
RPrLBaKCh6MRliP9V9cvUXcDVRvrYrUC3HCh57bwH2ZFE4om6LSUJgBf7YOhYNDX
owqw5Yaqv7CAV42dRCxjA/ATDBY3w8vfkfTKUY/JHCj8YMThJUL+Mg==
-----END RSA PRIVATE KEY-----
_EOF_

# Download amazon key so salt-master can access newly created minions via ssh. 
cat << _EOF_ > /etc/salt/amazon.pem && chmod 400 /etc/salt/amazon.pem
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAhHzy37/m5SXb68hF4pNFlQvaLMe/9okCeKUDuDtn9qrS2RB2Z9VZRdgGGSp9
rl6e/KRbg6Icw8/757RSVa1rN3rY7PCNsw5DMYWXVUgZ8AU9/d4J3c+cSX59iz/WzijGAh0dAUVs
8SJtVo0BZ3Pwdbd5azGTFXIcFGg5YfTWjyAq7PdC7ZztKigt/LD/d2DMqsFGNnRqeGbxDFX57aUi
SlVlJpIaJ2P+t0j8tpdIn/1U8p4/IrkhgVzzGxI4Z+a5AK4uPHAmpHIDDLETGz4pdD6EaxkfLzaJ
jp82wrVqx7e5h6yZaqpQqGLqw/aR9VohaF/mkfP1I0lVUofSaDg70QIDAQABAoIBAGwy5t7YiCbH
3m0WqAw8He11On6ruxgKGJySlxEUYvlN1Ng025483KVvoLtYuj93Qvws9hfwgvFfn+hAmaUi9Zbf
mt0WL4L1uOZupYKeWaBth40WkpQ1gvt6c+kO/8xp/BupzxBEtI3Rgd3XVjg4tT5N0rk6SVaQVGJO
I97d54QGmk1lSjO6ehSB/RjfsEIdAyqnTLIupYwP7Qt/r7uB7CJuTOU+WvqYrb74/X4BzT/98rrJ
p0d0QucKTAFTmaYxftbM9YI4bIzEI0eGeeQ4e71yJtjT+cK6HF7U4UFf3SkBt6wgaIwtwC9J1N+a
aNpKE4dsBgRFr2WPk0RccXoL5AECgYEA6GEM6GWElkbFdpGWdavFZM1CQMdib2ZDR8QWNjpRMJ+Q
lEBxQ2BqBE83fBs+1ZC+oQHseAVmKqYkPz7ENxedWdWiXE7D31+uQRkU8Bg97TKGHutJuC65FBM+
s9d1uoJbY4kUA/T9o45eFhDtUSX0XPYntUfMzqvR+jlJRBdS2eECgYEAkfSK4C9k9xtsgSogZZuF
fjuFDQ+B5/a+jRzVl+QvFloCW7wbk5btYy+zdvzxXjm2g/24wsGznAdrxXRcVxNCM6Z4QD/RYcBp
369RecYBWtSb9HOF9crpHuw9/JlqHKa/4z/J/WSnpvb6WupQFqEt0NY1B2D/k57CZf6pUKZy//EC
gYBwY+gLSnZK/GWqyBVeSjrJWyENFaH9QRePUT5w8dmsy6/wlA5zyODdvraWNtM4Fa6tTrHhBrN4
Myzaze+2uZwoA9RoEsxXb/5mi8v9p6vj2gjWUXQxOZ/YHsq3zqCpGT08MeNVWpuGDGhjAcLV+aZr
g76Gxfg/iQigni5aWXF/4QKBgEyqHqhTPL1vcjcGYa39WslLij+p/ZpSSRTmKGt4OCONc9+rlvCX
PmnzDFlb04yi0/PQudPS2v0CCOHWlQpH22Y18sQMwXaPEw2jkTBdiSiktKZaZ+sLghf0Dzs3ej1C
eVhskTTAQi+5WxeWLCs2zlH7si8GDDkGEyZv9Y+fXpiBAoGAaoA/V57sEYQOEdfIvpejOjrKh+1Y
OLRCQyO3k5LLYUEZTOxdr63vcssnPBaQFqJaMsjzdFMQ176KBPVOSw2WOu+CyyiV69Gj+Zl2f9wu
BAKfWHPhIR8Anuo58VbiAY8B0NLeiy8n4QL7eKZEbLlbd4edqrl7YrAaTelcCbvbqGw=
-----END RSA PRIVATE KEY-----
_EOF_

# clone salt configs from GitHub and put in the symlinks
git clone git@github.com:dcmn-com/deployment.git
git clone git@github.com:dcmn-com/piwik.git
ln -s /root/deployment/pillar /srv/pillar
ln -s /root/deployment/salt /srv/salt
ln -s /root/piwik/html /root/deployment/salt/piwik-prod/html
ln -s /root/piwik/log-import-stuff /root/deployment/salt/piwik-prod/log-import-stuff
# start the salt minion and accept the key
# salt-minion -d
sleep 5
salt-key -Ay
